In [1]:
import numpy as np
print("Imported numpy library")

Imported numpy library


In [4]:
print(f'Numpy version {np.__version__}')

Numpy version 1.19.2


In [5]:
# Create a null vector of size 10
print(np.zeros(shape = 10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# Create a vector with values ranging from 10 to 49
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# Reverse a vector
print(np.arange(10,50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# Find indices of non­zero elements from [1,2,0,0,4,0]
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


In [18]:
#Create a 3x3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
